<div id="myjquerymenu" class="jquerycssmenu" style="position:relative; z-index:9999;">
<ul>
    <li>
        <a href="#">Reportes</a>
        <ul>
            <li><a href="../dbnet.dbax/Home.aspx">Últimos EEFF reportados</a></li>
            <li><a href="../dbnet.dbax/ConsultaEmpresaPeriodo.aspx">Consulta empresa periodo</a></li>
            <li><a href="../dbnet.dbax/ConsultaGrupoSegmentos.aspx">Consulta grupos/segmentos por periodo</a></li>
            <li><a href="../dbnet.dbax/RepMultiPeriodo.aspx">Consulta comparativo empresa-periodos</a></li>
        </ul>
    </li>
    <li>
        <a href="#">Documentos</a>
        <ul>
            <li><a href="../dbnet.dbax/DescargaArchivos.aspx">Descarga de archivos</a></li>
            <li><a href="../dbnet.dbax/ListInfoDife.aspx">Reporte de cambios versiones de envío</a></li>
        </ul>
    </li>
    <li>
        <a href="#">Procesos</a>
        <ul>
        	<li><a href="../dbnet.dbax/CalculadorIndicadores.aspx">Cálculo de Indicadores</a></li>
        	<li><a href="../dbnet.dbax/CargaXBRLUsuario.aspx">Carga manual XBRL</a></li>
        	<li><a href="../librerias/archivos/DBNeT_PF_cuadros_tecnicos_seguros.pdf" target="_blank">Instrucciones BI</a></li>
        </ul>
    </li>
    <li>
	<a href="#">Administración</a>
	<ul>
		<li><a href="../dbnFw5/dbnFw5Listador.aspx?listado=L_DBAX_DEFI_PERS&MODO=M">Compañías</a></li>
		<li>
		    <a href="#">Reportes</a>
			<ul>
			    <li><a href="../dbnet.dbax/listadoReportes.aspx">Mantención reportes</a></li>
			    <li><a href="../dbnet.dbax/GeneraCntx.aspx">Mantención contextos</a></li>
			    <li><a href="../dbnet.dbax/InformeCntx.aspx">Contextos por informe</a></li>
			</ul>
		</li>
		<li>
		    <a href="#">Indicadores</a>
		    <ul>
			<li><a href="../dbnFw5/dbnFw5Listador.aspx?listado=L_LIST_INDI&MODO=M">Indicadores</a></li>
		    </ul>
		</li>
	</ul>
    </li>
    <li>
            <a href="#">Configuración</a>
            <ul>
                <li>
                    <a href="#">Básicos</a>
                        <ul>
                            <li> <a href="../dbnFw5/dbnFw5Listador.aspx?listado=L_XBRL_PROB&MODO=C">Estado de XBRL procesados</a></li>
    			</ul>
                </li>
            </ul>
    </li>
</ul>
<br style="clear: left" />
</div>